[package]
name = "rust-doom-demo"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
pixels = "0.13"
winit = "0.28"
winit_input_helper = "0.14"
clap = "4.4.3"
lazy_static = "1.4"